name: FakeBan
main: skyss0fly\FakeBan\Main
version: 1.0.0
api: 5.0.0
commands:
  fakeban:
    description: Fake ban a player
    usage: /fakeban <player> <reason>
    permission: FakeBan.use
permissions:
 FakeBan.use:
  description: fake ban command
  default: op
  
